### ISSUE TITLE
NameError: name 'kwargs' is not defined

### ISSUE THREAD

**Issue by maddin79** [niklaswais/gesp#7]
Hello, 

first thank for your work. I would like to use this program and installed it according to the README. But if I run the command `python -m gesp -p /to/my/save/folder` i get the following error message:

````
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/mdrees/Programming/PythonProjects/gesp/dist/venv/lib/python3.11/site-packages/gesp/__main__.py", line 12, in <module>
    from .spiders import bb, be, bund, bw, by, hb, hh, he, mv, ni, nw, rp, sh, sl, sn, st, th
  File "/home/mdrees/Programming/PythonProjects/gesp/dist/venv/lib/python3.11/site-packages/gesp/spiders/bw.py", line 9, in <module>
    class SpdrBW(scrapy.Spider):
  File "/home/mdrees/Programming/PythonProjects/gesp/dist/venv/lib/python3.11/site-packages/gesp/spiders/bw.py", line 26, in SpdrBW
    def __init__(self, path, courts="", states="", fp=False, domains="", store_docId=False, postprocess=False, wait=False **kwargs):
                                                                                                                            ^^^^^^
NameError: name 'kwargs' is not defined
````

I'm pretty new to python and I don't know if I miss a package or if it is a error in the program. Could you please give me a hint to solve it?

Best
Martin

**Comment by niklaswais** [comment]
It was a bug, thank you for pointing it out! Should be fixed now.

**Comment by maddin79** [comment]
Hey @niklaswais,

works perfect now. Thank you very much.
